version: '3.8'

services:
  postgres-15:
    image: postgres:15
    container_name: PostgreSQL-15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin@123
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - postgres_15_network   

networks:
  postgres_15_network:       
    driver: bridge         

volumes:
  pg_data: