version: '3.8'

services:
  postgres-14:
    image: postgres:14
    container_name: PostgreSQL-14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin@123
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - postgres_14_network

networks:
  postgres_14_network:       
    driver: bridge         

volumes:
  pg_data: