version: '3.8'

services:
  postgres-9:
    image: postgres:9.6
    container_name: PostgreSQL-9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin@123
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - postgres_9_network

networks:
  postgres_9_network:       
    driver: bridge         

volumes:
  pg_data: